# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy_msg.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proxy_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproxy_msg.proto\x12\x08\x63onsumer\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\rProxyResponse\x12\r\n\x05proxy\x18\x01 \x01(\t\"#\n\x12\x46inishProxyRequest\x12\r\n\x05proxy\x18\x01 \x01(\t\"6\n\x0cPingResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc4\x01\n\x08\x43onsumer\x12;\n\x08GetProxy\x12\x16.google.protobuf.Empty\x1a\x17.consumer.ProxyResponse\x12\x43\n\x0b\x46inishProxy\x12\x1c.consumer.FinishProxyRequest\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.consumer.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROXYRESPONSE']._serialized_start=58
  _globals['_PROXYRESPONSE']._serialized_end=88
  _globals['_FINISHPROXYREQUEST']._serialized_start=90
  _globals['_FINISHPROXYREQUEST']._serialized_end=125
  _globals['_PINGRESPONSE']._serialized_start=127
  _globals['_PINGRESPONSE']._serialized_end=181
  _globals['_CONSUMER']._serialized_start=184
  _globals['_CONSUMER']._serialized_end=380
# @@protoc_insertion_point(module_scope)
